### ISSUE TITLE
integration with openwrt

### ISSUE THREAD

**Issue by vavrecan** [nekromant/fastbootd#2]
Hello,
I was wondering, how do you actually integrate fastbootd with openwrt at all?
Do you replace preinit script? And how do you compile initrd.bin and secondstage.bin with openwrt toolchain?
Thank you

**Comment by vavrecan** [comment]
I do not understand how it makes booting actually faster since /etc/init.d/ is 7th in the boot sequence: https://wiki.openwrt.org/doc/techref/preinit_mount

https://github.com/nekromant/openwrt-feed/blob/master/fastbootd/Makefile 
https://github.com/nekromant/fastbootd/blob/master/etc/init.d/fastbootd
and init.d script seems to look for /tftp/zImage-blade - how did you build this image?

**Comment by nekromant** [comment]
I think you didn't understand the setup correctly. It's just a quick hack for the hardware setup I had for a while: 
I had an OpenWRT router and a few odroid-x2 boxes connected to it. I used usb connectivity since 400Mbit rndis is faster than 100mbps network and needed to boot those off OpenWRT. 
Basically fastbootd sits there as a daemon and sends out zImage to any fastboot device that appears in system. That's it. Odroids have 'fastboot' in their bootcmd so whenever they are rebooted, they receive payload from host.
